name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup uv & Python
      uses: astral-sh/setup-uv@v6
      with:
        pyproject-file: "pyproject.toml"

    - name: Install dependencies
      run: |
        uv sync --frozen

    - name: Run tests
      run: |
        uv run pytest tests/ -v --cov=src --cov-report=term-missing:skip-covered --cov-report=html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 7

    - name: Display coverage summary
      if: always()
      run: |
        echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        uv run coverage report >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
